Various string fixes
nicolasbrailo/PianOli pull request #80
Opened 2023-10-16 15:19 UTC by comradekingu

2023-10-16 21:39 UTC, juleskers requested changes
Hi and welcome, @comradekingu!

Thank you very much for your contribution!
it always warms our heart when someone appreciates our App enough to contribute back :heart:

I've reviewed your changes, and there's a few things I'd like to keep, but also some good improvements 👍 

@pserwylo, can I get  your input 9n the correct spelling of Incy Wincy? (I learned "Itsy Bitsy", but I'd prefer Aussie over American 😉)

2023-10-16 21:39 UTC, juleskers commented on app/src/main/res/values/strings.xml
> +    <string name="some_info_about_this_app_title"><b><big><big>PianOli is copylefted libre software.</big></big></b></string>
While I, personally, understand the difference between "copyleft" and "open source", PianOli is aimed at a very broad, non-technical audience, who we don't expect to comprehend the difference.

Fact remains that "open source" the best known "marketing label" for non-technical people, so I'd prefer to keep that.

2023-10-16 21:39 UTC, juleskers commented on app/src/main/res/values/strings.xml
> +    <string name="some_info_about_this_app">SSend suggestions, feature requests and bug reports to the <a href="https://github.com/nicolasbrailo/PianOli">project website</a>.</string>
This reads a lot nicer than before 👍
although it seems the first letter got doubled up ("SSend")

2023-10-16 21:39 UTC, juleskers commented on app/src/main/res/values/strings.xml
> +    <string name="melody_insy_winsy_spider">Incy Winsy Spider</string>
In honour of our Australian maintainer, @pserwylo, we currently have the Australian spelling.

The again, I do see that Wikipedia says Australia spells it "Incy Wincy" (c-c, not c-s).

I hesitate to correct a native Australian in his own language, so...
Peter, what looks better to your native eye?

2023-10-17 01:13 UTC, pserwylo commented on app/src/main/res/values/strings.xml
> +    <string name="melody_insy_winsy_spider">Incy Winsy Spider</string>
Whoops, spelling is not my strong point. On reflection, definitely "Incy Wincy". Ta.

2023-10-17 01:28 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="melody_insy_winsy_spider">Incy Winsy Spider</string>
I went by https://en.wikipedia.org/wiki/Itsy_Bitsy_Spider
It means ~very small

2023-10-17 01:29 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="some_info_about_this_app">SSend suggestions, feature requests and bug reports to the <a href="https://github.com/nicolasbrailo/PianOli">project website</a>.</string>
```suggestion
    <string name="some_info_about_this_app">Send suggestions, feature requests and bug reports to the <a href="https://github.com/nicolasbrailo/PianOli">project website</a>.</string>
```

2023-10-17 02:07 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="some_info_about_this_app_title"><b><big><big>PianOli is copylefted libre software.</big></big></b></string>
You will be hard pressed to find a single non-tecnical person that understands "open source" to be anything other than ~gratis, which it doesn't mean, but prevented from required to be.
"Freeware" is however very well-known as a concept, and this is a success of sharing software.
And then English robs us of "shareware", in pertaining to ideals of decentralization.
In the overlap, is the important bit that this happens to be similar to freeware or shareware in one capacity or another?
I maintain that the poignant point is the transfer of powers, or liberties if you will — all of which are important to marketeers and non-technical people alike.
And then we lose the ability to decide which licenses follow all freedoms even further by allowing the OSI to dictate "open source" compliance.

If anything "open source", which can also be misspelt "open-source" lends itself to specify "~source that is in the open", for which the direct translation, is often exactly ~"open_source",
only now in a manner that isn't trademarked… Oh dear.
For any reach it has, in English, that is mostly all counterproductive for people such as yourself that stand to benefit from non-technical people catching on. Same boat.

Not only does it not even _mean_ copylefted, but also sells itself short by conflating that to mean whatever it is that all this marketing hasn't been able to convey.
For marketeers "open source" is a success of being palatable to businesses. At first as something purposely focused on things other than ethics, and now as something that avoids
responsibility, again.
Everything else is merit, much like freeware can be of better or worse quality.
The control group is "free software" which tries to focus on ethics, but falls into the trap of not being perceivable from ~"gratisware" in English. It too has failed to do anything.

If the market favours a proprietary internal-cost driven model then, or a nearly all open source, but crucially not-model now, I maintain that what you are doing is not the same, hasn't ever been, and neither could or should not be thought of as such because of market conditions.

There is a marketable difference between the sort of things things other than "copylefted" software lends itself to, and what happens to be the penchant of people such as yourself.
That doesn't go away. It is a integral difference, and you stand to benefit just as much as the industry of other ideals has understood to muddy the waters.

People do care about their babies, and right now the people targeting babies fall into exactly two camps, because there are zero examples of malice there in the copyleft world.

2023-10-17 02:07 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="some_info_about_this_app_title"><b><big><big>PianOli is copylefted libre software.</big></big></b></string>
```suggestion
    <string name="some_info_about_this_app_title"><b><big><big>PianOli is open-source!</big></big></b></string>
```

2023-10-17 10:03 UTC, pserwylo commented on app/src/main/res/values/strings.xml
> +    <string name="some_info_about_this_app_title"><b><big><big>PianOli is copylefted libre software.</big></big></b></string>
Thanks @comradekingu. Not disagreeing with the philosophical angle at all, but in the name of simplicity, will leave it as Open Source for now.

2023-10-17 10:03 UTC, merged